### ISSUE TITLE
Nexus Repo Login

### ISSUE THREAD

**Issue by jaredbarranco** [mulesoft-labs/data-weave-playground-ui#2]
I am running very large json files with Playground and I'm running into resource constraints on the browser version. I found this repo and would like to use it locally as I have abundant hardware headspace.

Seems like I can't actually use this?

**Comment by machaval** [comment]
This is just the UI, and it can not be compiled as depends on internal libraries. I suggest to use the [VSCode plugin](https://marketplace.visualstudio.com/items?itemName=MuleSoftInc.dataweave) or running the playground with the [cli](https://github.com/mulesoft-labs/data-weave-cli) `dw spell --eval Playground`
